### ISSUE TITLE
Django Pattern Library overrides not working

### ISSUE THREAD

**Issue by nicklee** [denshoproject/encyc-tng#60]
Typically with DPL you can provide overrides to allow you to fake content in the pattern library, however the usual overrides don't seem to be working.

For example an image can be overriden with 

```
tags:
  image:
    author.image fill-340x340 format-webp as image:
      target_var: image
      raw:
        url: '//picsum.photos/340/340.webp'

```

Or a streamfield can be overriden with:

```
tags:
  include_block:
    page.body:
      template_name: '_pattern_library_only/streamfield/body_example.html'
```

This is detailed here, I suspect this aspect hasn't been implemented yet?:
https://torchbox.github.io/django-pattern-library/guides/overriding-template-tags/#overriding-examples
