### ISSUE TITLE
Broken home page layout

### ISSUE THREAD

**Issue by gjost** [denshoproject/encyc-tng#76]
https://encycstage.densho.org/pattern-library/pattern/patterns/pages/home_page/home_page.html

The orange background on the home page is broken and the hero image is missing.

Template config context contains an `image_url`
```
context:
  page:
    title: Densho Encyclopedia
    hero:
      title: Discover the history of the Japanese American incarceration during WWII
      ...
    image_url: https://placehold.co/400x400
    topics:
      ...
```
but the Template source does not have an image:
```
{% extends "base.html" %}
{% load static %}

{% block body_class %}template-homepage app--orange{% endblock %}

{% block content %}
    <div class="page">
        <header class="page__header">
            {% include "patterns/components/hero/hero.html" with hero=page.hero %}
        </header>
        <div class="page__content">
            {% include "patterns/components/topics/topics.html" with topics=page.topics %}
        </div>
    </div>
{% endblock content %}
```
